window.mock = {
    "position":100420,
    "name":"难得",
    "rows":{
        "2":{
            "startPoint":"47590",
            "duration":"7715",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"808",
                    "str":"那"
                },
                {
                    "startPoint":"808",
                    "duration":"202",
                    "str":"时"
                },
                {
                    "startPoint":"1010",
                    "duration":"306",
                    "str":"我"
                },
                {
                    "startPoint":"1316",
                    "duration":"660",
                    "str":"们"
                },
                {
                    "startPoint":"1976",
                    "duration":"254",
                    "str":"不"
                },
                {
                    "startPoint":"2230",
                    "duration":"306",
                    "str":"害"
                },
                {
                    "startPoint":"2536",
                    "duration":"1067",
                    "str":"怕"
                },
                {
                    "startPoint":"3603",
                    "duration":"507",
                    "str":"犯"
                },
                {
                    "startPoint":"4110",
                    "duration":"3605",
                    "str":"错"
                }
            ]
        },
        "3":{
            "startPoint":"55005",
            "duration":"6906",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"757",
                    "str":"那"
                },
                {
                    "startPoint":"757",
                    "duration":"254",
                    "str":"时"
                },
                {
                    "startPoint":"1011",
                    "duration":"355",
                    "str":"以"
                },
                {
                    "startPoint":"1366",
                    "duration":"762",
                    "str":"为"
                },
                {
                    "startPoint":"2128",
                    "duration":"407",
                    "str":"天"
                },
                {
                    "startPoint":"2535",
                    "duration":"303",
                    "str":"空"
                },
                {
                    "startPoint":"2838",
                    "duration":"1424",
                    "str":"多"
                },
                {
                    "startPoint":"4262",
                    "duration":"460",
                    "str":"辽"
                },
                {
                    "startPoint":"4722",
                    "duration":"2184",
                    "str":"阔"
                }
            ]
        },
        "4":{
            "startPoint":"61611",
            "duration":"7612",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"655",
                    "str":"朋"
                },
                {
                    "startPoint":"655",
                    "duration":"357",
                    "str":"友"
                },
                {
                    "startPoint":"1012",
                    "duration":"303",
                    "str":"都"
                },
                {
                    "startPoint":"1315",
                    "duration":"1118",
                    "str":"说"
                },
                {
                    "startPoint":"2433",
                    "duration":"507",
                    "str":"你"
                },
                {
                    "startPoint":"2940",
                    "duration":"508",
                    "str":"后"
                },
                {
                    "startPoint":"3448",
                    "duration":"408",
                    "str":"来"
                },
                {
                    "startPoint":"3856",
                    "duration":"659",
                    "str":"变"
                },
                {
                    "startPoint":"4515",
                    "duration":"305",
                    "str":"真"
                },
                {
                    "startPoint":"4820",
                    "duration":"2792",
                    "str":"多"
                }
            ]
        },
        "5":{
            "startPoint":"68923",
            "duration":"8883",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"708",
                    "str":"总"
                },
                {
                    "startPoint":"708",
                    "duration":"354",
                    "str":"是"
                },
                {
                    "startPoint":"1062",
                    "duration":"304",
                    "str":"避"
                },
                {
                    "startPoint":"1366",
                    "duration":"814",
                    "str":"谈"
                },
                {
                    "startPoint":"2180",
                    "duration":"405",
                    "str":"纯"
                },
                {
                    "startPoint":"2585",
                    "duration":"356",
                    "str":"真"
                },
                {
                    "startPoint":"2941",
                    "duration":"306",
                    "str":"坦"
                },
                {
                    "startPoint":"3247",
                    "duration":"812",
                    "str":"白"
                },
                {
                    "startPoint":"4059",
                    "duration":"508",
                    "str":"那"
                },
                {
                    "startPoint":"4567",
                    "duration":"355",
                    "str":"时"
                },
                {
                    "startPoint":"4922",
                    "duration":"3961",
                    "str":"候"
                }
            ]
        },
        "6":{
            "startPoint":"77506",
            "duration":"5430",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"758",
                    "str":"体"
                },
                {
                    "startPoint":"758",
                    "duration":"253",
                    "str":"贴"
                },
                {
                    "startPoint":"1011",
                    "duration":"407",
                    "str":"的"
                },
                {
                    "startPoint":"1418",
                    "duration":"710",
                    "str":"人"
                },
                {
                    "startPoint":"2128",
                    "duration":"458",
                    "str":"不"
                },
                {
                    "startPoint":"2586",
                    "duration":"304",
                    "str":"再"
                },
                {
                    "startPoint":"2890",
                    "duration":"611",
                    "str":"追"
                },
                {
                    "startPoint":"3501",
                    "duration":"354",
                    "str":"问"
                },
                {
                    "startPoint":"3855",
                    "duration":"1575",
                    "str":"我"
                }
            ]
        },
        "7":{
            "startPoint":"82636",
            "duration":"5835",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"808",
                    "str":"只"
                },
                {
                    "startPoint":"808",
                    "duration":"813",
                    "str":"说"
                },
                {
                    "startPoint":"1621",
                    "duration":"457",
                    "str":"你"
                },
                {
                    "startPoint":"2078",
                    "duration":"254",
                    "str":"也"
                },
                {
                    "startPoint":"2332",
                    "duration":"457",
                    "str":"有"
                },
                {
                    "startPoint":"2789",
                    "duration":"761",
                    "str":"梦"
                },
                {
                    "startPoint":"3550",
                    "duration":"457",
                    "str":"他"
                },
                {
                    "startPoint":"4007",
                    "duration":"254",
                    "str":"也"
                },
                {
                    "startPoint":"4261",
                    "duration":"405",
                    "str":"有"
                },
                {
                    "startPoint":"4666",
                    "duration":"1169",
                    "str":"梦"
                }
            ]
        },
        "8":{
            "startPoint":"88171",
            "duration":"4972",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"656",
                    "str":"虽"
                },
                {
                    "startPoint":"656",
                    "duration":"203",
                    "str":"然"
                },
                {
                    "startPoint":"859",
                    "duration":"406",
                    "str":"难"
                },
                {
                    "startPoint":"1265",
                    "duration":"457",
                    "str":"得"
                },
                {
                    "startPoint":"1722",
                    "duration":"508",
                    "str":"不"
                },
                {
                    "startPoint":"2230",
                    "duration":"457",
                    "str":"必"
                },
                {
                    "startPoint":"2687",
                    "duration":"863",
                    "str":"心"
                },
                {
                    "startPoint":"3550",
                    "duration":"1422",
                    "str":"痛"
                }
            ]
        },
        "9":{
            "startPoint":"92843",
            "duration":"7867",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"859",
                    "str":"我"
                },
                {
                    "startPoint":"859",
                    "duration":"407",
                    "str":"以"
                },
                {
                    "startPoint":"1266",
                    "duration":"456",
                    "str":"为"
                },
                {
                    "startPoint":"1722",
                    "duration":"406",
                    "str":"我"
                },
                {
                    "startPoint":"2128",
                    "duration":"559",
                    "str":"成"
                },
                {
                    "startPoint":"2687",
                    "duration":"457",
                    "str":"熟"
                },
                {
                    "startPoint":"3144",
                    "duration":"306",
                    "str":"以"
                },
                {
                    "startPoint":"3450",
                    "duration":"253",
                    "str":"为"
                },
                {
                    "startPoint":"3703",
                    "duration":"406",
                    "str":"从"
                },
                {
                    "startPoint":"4109",
                    "duration":"305",
                    "str":"此"
                },
                {
                    "startPoint":"4414",
                    "duration":"711",
                    "str":"就"
                },
                {
                    "startPoint":"5125",
                    "duration":"407",
                    "str":"自"
                },
                {
                    "startPoint":"5532",
                    "duration":"2335",
                    "str":"由"
                }
            ]
        },
        "10":{
            "startPoint":"100410",
            "duration":"7813",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"809",
                    "str":"我"
                },
                {
                    "startPoint":"809",
                    "duration":"457",
                    "str":"尝"
                },
                {
                    "startPoint":"1266",
                    "duration":"406",
                    "str":"试"
                },
                {
                    "startPoint":"1672",
                    "duration":"407",
                    "str":"着"
                },
                {
                    "startPoint":"2079",
                    "duration":"507",
                    "str":"快"
                },
                {
                    "startPoint":"2586",
                    "duration":"557",
                    "str":"乐"
                },
                {
                    "startPoint":"3143",
                    "duration":"255",
                    "str":"快"
                },
                {
                    "startPoint":"3398",
                    "duration":"203",
                    "str":"乐"
                },
                {
                    "startPoint":"3601",
                    "duration":"458",
                    "str":"却"
                },
                {
                    "startPoint":"4059",
                    "duration":"304",
                    "str":"不"
                },
                {
                    "startPoint":"4363",
                    "duration":"657",
                    "str":"陪"
                },
                {
                    "startPoint":"5020",
                    "duration":"408",
                    "str":"着"
                },
                {
                    "startPoint":"5428",
                    "duration":"2385",
                    "str":"我"
                }
            ]
        },
        "11":{
            "startPoint":"107923",
            "duration":"7216",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"757",
                    "str":"爱"
                },
                {
                    "startPoint":"757",
                    "duration":"508",
                    "str":"没"
                },
                {
                    "startPoint":"1265",
                    "duration":"406",
                    "str":"有"
                },
                {
                    "startPoint":"1671",
                    "duration":"406",
                    "str":"回"
                },
                {
                    "startPoint":"2077",
                    "duration":"356",
                    "str":"来"
                },
                {
                    "startPoint":"2433",
                    "duration":"1524",
                    "str":"了"
                },
                {
                    "startPoint":"3957",
                    "duration":"457",
                    "str":"你"
                },
                {
                    "startPoint":"4414",
                    "duration":"508",
                    "str":"已"
                },
                {
                    "startPoint":"4922",
                    "duration":"457",
                    "str":"经"
                },
                {
                    "startPoint":"5379",
                    "duration":"304",
                    "str":"离"
                },
                {
                    "startPoint":"5683",
                    "duration":"406",
                    "str":"开"
                },
                {
                    "startPoint":"6089",
                    "duration":"1127",
                    "str":"我"
                }
            ]
        },
        "12":{
            "startPoint":"114839",
            "duration":"8225",
            "content":[
                {
                    "startPoint":"0",
                    "duration":"910",
                    "str":"回"
                },
                {
                    "startPoint":"910",
                    "duration":"408",
                    "str":"忆"
                },
                {
                    "startPoint":"1318",
                    "duration":"457",
                    "str":"紧"
                },
                {
                    "startPoint":"1775",
                    "duration":"457",
                    "str":"紧"
                },
                {
                    "startPoint":"2232",
                    "duration":"457",
                    "str":"缠"
                },
                {
                    "startPoint":"2689",
                    "duration":"305",
                    "str":"着"
                },
                {
                    "startPoint":"2994",
                    "duration":"1015",
                    "str":"我"
                },
                {
                    "startPoint":"4009",
                    "duration":"508",
                    "str":"像"
                },
                {
                    "startPoint":"4517",
                    "duration":"508",
                    "str":"当"
                },
                {
                    "startPoint":"5025",
                    "duration":"457",
                    "str":"初"
                },
                {
                    "startPoint":"5482",
                    "duration":"254",
                    "str":"不"
                },
                {
                    "startPoint":"5736",
                    "duration":"306",
                    "str":"肯"
                },
                {
                    "startPoint":"6042",
                    "duration":"861",
                    "str":"放"
                },
                {
                    "startPoint":"6903",
                    "duration":"1322",
                    "str":"手"
                }
            ]
        }
    },
    "currentRowIndex":10,
    "currentWordIndex":0
};
