
window.mock = {
  "position":45582+201/2,
  "name":"光辉岁月",
  "currentRowIndex":4,
  "currentWordIndex":0,
  "rows":{
    "2":{
      "startPoint":"35924",
      "duration":"3961",
      "content":[
        {
          "startPoint":"0",
          "duration":"201",
          "str":"仿"
        },
        {
          "startPoint":"201",
          "duration":"250",
          "str":"佛"
        },
        {
          "startPoint":"451",
          "duration":"216",
          "str":"带"
        },
        {
          "startPoint":"667",
          "duration":"394",
          "str":"点"
        },
        {
          "startPoint":"1061",
          "duration":"1750",
          "str":"唏"
        },
        {
          "startPoint":"2811",
          "duration":"1150",
          "str":"嘘"
        }
      ]
    },
    "3":{
      "startPoint":"41185",
      "duration":"3501",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"黑"
        },
        {
          "startPoint":"250",
          "duration":"199",
          "str":"色"
        },
        {
          "startPoint":"449",
          "duration":"252",
          "str":"肌"
        },
        {
          "startPoint":"701",
          "duration":"149",
          "str":"肤"
        },
        {
          "startPoint":"850",
          "duration":"401",
          "str":"给"
        },
        {
          "startPoint":"1251",
          "duration":"250",
          "str":"他"
        },
        {
          "startPoint":"1501",
          "duration":"450",
          "str":"的"
        },
        {
          "startPoint":"1951",
          "duration":"450",
          "str":"意"
        },
        {
          "startPoint":"2401",
          "duration":"1100",
          "str":"义"
        }
      ]
    },
    "4":{
      "startPoint":"45582",
      "duration":"2400",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"是"
        },
        {
          "startPoint":"250",
          "duration":"200",
          "str":"一"
        },
        {
          "startPoint":"450",
          "duration":"250",
          "str":"生"
        },
        {
          "startPoint":"700",
          "duration":"400",
          "str":"奉"
        },
        {
          "startPoint":"1100",
          "duration":"1300",
          "str":"献"
        }
      ]
    },
    "5":{
      "startPoint":"48783",
      "duration":"3700",
      "content":[
        {
          "startPoint":"0",
          "duration":"249",
          "str":"肤"
        },
        {
          "startPoint":"249",
          "duration":"251",
          "str":"色"
        },
        {
          "startPoint":"500",
          "duration":"250",
          "str":"斗"
        },
        {
          "startPoint":"750",
          "duration":"450",
          "str":"争"
        },
        {
          "startPoint":"1200",
          "duration":"2500",
          "str":"中"
        }
      ]
    },
    "6":{
      "startPoint":"54233",
      "duration":"5149",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"年"
        },
        {
          "startPoint":"250",
          "duration":"249",
          "str":"月"
        },
        {
          "startPoint":"499",
          "duration":"251",
          "str":"把"
        },
        {
          "startPoint":"750",
          "duration":"350",
          "str":"拥"
        },
        {
          "startPoint":"1100",
          "duration":"400",
          "str":"有"
        },
        {
          "startPoint":"1500",
          "duration":"450",
          "str":"变"
        },
        {
          "startPoint":"1950",
          "duration":"400",
          "str":"作"
        },
        {
          "startPoint":"2350",
          "duration":"1600",
          "str":"失"
        },
        {
          "startPoint":"3950",
          "duration":"1199",
          "str":"去"
        }
      ]
    },
    "7":{
      "startPoint":"60683",
      "duration":"5549",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"疲"
        },
        {
          "startPoint":"300",
          "duration":"250",
          "str":"倦"
        },
        {
          "startPoint":"550",
          "duration":"250",
          "str":"的"
        },
        {
          "startPoint":"800",
          "duration":"350",
          "str":"双"
        },
        {
          "startPoint":"1150",
          "duration":"350",
          "str":"眼"
        },
        {
          "startPoint":"1500",
          "duration":"400",
          "str":"带"
        },
        {
          "startPoint":"1900",
          "duration":"451",
          "str":"着"
        },
        {
          "startPoint":"2351",
          "duration":"1550",
          "str":"期"
        },
        {
          "startPoint":"3901",
          "duration":"1648",
          "str":"望"
        }
      ]
    },
    "8":{
      "startPoint":"67132",
      "duration":"3252",
      "content":[
        {
          "startPoint":"0",
          "duration":"301",
          "str":"今"
        },
        {
          "startPoint":"301",
          "duration":"199",
          "str":"天"
        },
        {
          "startPoint":"500",
          "duration":"200",
          "str":"只"
        },
        {
          "startPoint":"700",
          "duration":"201",
          "str":"有"
        },
        {
          "startPoint":"901",
          "duration":"300",
          "str":"残"
        },
        {
          "startPoint":"1201",
          "duration":"201",
          "str":"留"
        },
        {
          "startPoint":"1402",
          "duration":"500",
          "str":"的"
        },
        {
          "startPoint":"1902",
          "duration":"450",
          "str":"躯"
        },
        {
          "startPoint":"2352",
          "duration":"900",
          "str":"壳"
        }
      ]
    },
    "9":{
      "startPoint":"70665",
      "duration":"2850",
      "content":[
        {
          "startPoint":"0",
          "duration":"299",
          "str":"迎"
        },
        {
          "startPoint":"299",
          "duration":"201",
          "str":"接"
        },
        {
          "startPoint":"500",
          "duration":"449",
          "str":"光"
        },
        {
          "startPoint":"949",
          "duration":"351",
          "str":"辉"
        },
        {
          "startPoint":"1300",
          "duration":"600",
          "str":"岁"
        },
        {
          "startPoint":"1900",
          "duration":"950",
          "str":"月"
        }
      ]
    },
    "10":{
      "startPoint":"73965",
      "duration":"4703",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"风"
        },
        {
          "startPoint":"350",
          "duration":"450",
          "str":"雨"
        },
        {
          "startPoint":"800",
          "duration":"250",
          "str":"中"
        },
        {
          "startPoint":"1050",
          "duration":"552",
          "str":"抱"
        },
        {
          "startPoint":"1602",
          "duration":"450",
          "str":"紧"
        },
        {
          "startPoint":"2052",
          "duration":"1651",
          "str":"自"
        },
        {
          "startPoint":"3703",
          "duration":"1000",
          "str":"由"
        }
      ]
    },
    "11":{
      "startPoint":"80118",
      "duration":"3251",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"一"
        },
        {
          "startPoint":"250",
          "duration":"200",
          "str":"生"
        },
        {
          "startPoint":"450",
          "duration":"200",
          "str":"经"
        },
        {
          "startPoint":"650",
          "duration":"250",
          "str":"过"
        },
        {
          "startPoint":"900",
          "duration":"300",
          "str":"彷"
        },
        {
          "startPoint":"1200",
          "duration":"300",
          "str":"徨"
        },
        {
          "startPoint":"1500",
          "duration":"451",
          "str":"的"
        },
        {
          "startPoint":"1951",
          "duration":"450",
          "str":"挣"
        },
        {
          "startPoint":"2401",
          "duration":"850",
          "str":"扎"
        }
      ]
    },
    "12":{
      "startPoint":"83789",
      "duration":"2653",
      "content":[
        {
          "startPoint":"0",
          "duration":"201",
          "str":"自"
        },
        {
          "startPoint":"201",
          "duration":"250",
          "str":"信"
        },
        {
          "startPoint":"451",
          "duration":"350",
          "str":"可"
        },
        {
          "startPoint":"801",
          "duration":"349",
          "str":"改"
        },
        {
          "startPoint":"1150",
          "duration":"292",
          "str":"变"
        },
        {
          "startPoint":"1442",
          "duration":"361",
          "str":"未"
        },
        {
          "startPoint":"1803",
          "duration":"850",
          "str":"来"
        }
      ]
    },
    "13":{
      "startPoint":"86992",
      "duration":"3751",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"问"
        },
        {
          "startPoint":"350",
          "duration":"401",
          "str":"谁"
        },
        {
          "startPoint":"751",
          "duration":"200",
          "str":"又"
        },
        {
          "startPoint":"951",
          "duration":"549",
          "str":"能"
        },
        {
          "startPoint":"1500",
          "duration":"451",
          "str":"做"
        },
        {
          "startPoint":"1951",
          "duration":"1800",
          "str":"到"
        }
      ]
    },
    "14":{
      "startPoint":"102638",
      "duration":"3901",
      "content":[
        {
          "startPoint":"0",
          "duration":"301",
          "str":"可"
        },
        {
          "startPoint":"301",
          "duration":"250",
          "str":"否"
        },
        {
          "startPoint":"551",
          "duration":"149",
          "str":"不"
        },
        {
          "startPoint":"700",
          "duration":"251",
          "str":"分"
        },
        {
          "startPoint":"951",
          "duration":"400",
          "str":"肤"
        },
        {
          "startPoint":"1351",
          "duration":"251",
          "str":"色"
        },
        {
          "startPoint":"1602",
          "duration":"400",
          "str":"的"
        },
        {
          "startPoint":"2002",
          "duration":"550",
          "str":"界"
        },
        {
          "startPoint":"2552",
          "duration":"1349",
          "str":"限"
        }
      ]
    },
    "15":{
      "startPoint":"107170",
      "duration":"2251",
      "content":[
        {
          "startPoint":"0",
          "duration":"301",
          "str":"愿"
        },
        {
          "startPoint":"301",
          "duration":"199",
          "str":"这"
        },
        {
          "startPoint":"500",
          "duration":"250",
          "str":"土"
        },
        {
          "startPoint":"750",
          "duration":"301",
          "str":"地"
        },
        {
          "startPoint":"1051",
          "duration":"1200",
          "str":"里"
        }
      ]
    },
    "16":{
      "startPoint":"110420",
      "duration":"4001",
      "content":[
        {
          "startPoint":"0",
          "duration":"401",
          "str":"不"
        },
        {
          "startPoint":"401",
          "duration":"49",
          "str":"分"
        },
        {
          "startPoint":"450",
          "duration":"250",
          "str":"你"
        },
        {
          "startPoint":"700",
          "duration":"451",
          "str":"我"
        },
        {
          "startPoint":"1151",
          "duration":"1749",
          "str":"高"
        },
        {
          "startPoint":"2900",
          "duration":"1101",
          "str":"低"
        }
      ]
    },
    "17":{
      "startPoint":"115771",
      "duration":"3357",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"缤"
        },
        {
          "startPoint":"250",
          "duration":"199",
          "str":"纷"
        },
        {
          "startPoint":"449",
          "duration":"201",
          "str":"色"
        },
        {
          "startPoint":"650",
          "duration":"256",
          "str":"彩"
        },
        {
          "startPoint":"906",
          "duration":"351",
          "str":"闪"
        },
        {
          "startPoint":"1257",
          "duration":"250",
          "str":"出"
        },
        {
          "startPoint":"1507",
          "duration":"350",
          "str":"的"
        },
        {
          "startPoint":"1857",
          "duration":"450",
          "str":"美"
        },
        {
          "startPoint":"2307",
          "duration":"1050",
          "str":"丽"
        }
      ]
    },
    "18":{
      "startPoint":"120228",
      "duration":"2140",
      "content":[
        {
          "startPoint":"0",
          "duration":"201",
          "str":"是"
        },
        {
          "startPoint":"201",
          "duration":"307",
          "str":"因"
        },
        {
          "startPoint":"508",
          "duration":"381",
          "str":"它"
        },
        {
          "startPoint":"889",
          "duration":"201",
          "str":"没"
        },
        {
          "startPoint":"1090",
          "duration":"1050",
          "str":"有"
        }
      ]
    },
    "19":{
      "startPoint":"123468",
      "duration":"4350",
      "content":[
        {
          "startPoint":"0",
          "duration":"249",
          "str":"分"
        },
        {
          "startPoint":"249",
          "duration":"201",
          "str":"开"
        },
        {
          "startPoint":"450",
          "duration":"200",
          "str":"每"
        },
        {
          "startPoint":"650",
          "duration":"500",
          "str":"种"
        },
        {
          "startPoint":"1150",
          "duration":"1700",
          "str":"色"
        },
        {
          "startPoint":"2850",
          "duration":"1500",
          "str":"彩"
        }
      ]
    },
    "20":{
      "startPoint":"128768",
      "duration":"5150",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"年"
        },
        {
          "startPoint":"350",
          "duration":"199",
          "str":"月"
        },
        {
          "startPoint":"549",
          "duration":"251",
          "str":"把"
        },
        {
          "startPoint":"800",
          "duration":"400",
          "str":"拥"
        },
        {
          "startPoint":"1200",
          "duration":"350",
          "str":"有"
        },
        {
          "startPoint":"1550",
          "duration":"400",
          "str":"变"
        },
        {
          "startPoint":"1950",
          "duration":"400",
          "str":"作"
        },
        {
          "startPoint":"2350",
          "duration":"1650",
          "str":"失"
        },
        {
          "startPoint":"4000",
          "duration":"1150",
          "str":"去"
        }
      ]
    },
    "21":{
      "startPoint":"135169",
      "duration":"5401",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"疲"
        },
        {
          "startPoint":"350",
          "duration":"250",
          "str":"倦"
        },
        {
          "startPoint":"600",
          "duration":"251",
          "str":"的"
        },
        {
          "startPoint":"851",
          "duration":"349",
          "str":"双"
        },
        {
          "startPoint":"1200",
          "duration":"450",
          "str":"眼"
        },
        {
          "startPoint":"1650",
          "duration":"401",
          "str":"带"
        },
        {
          "startPoint":"2051",
          "duration":"399",
          "str":"着"
        },
        {
          "startPoint":"2450",
          "duration":"1550",
          "str":"期"
        },
        {
          "startPoint":"4000",
          "duration":"1401",
          "str":"望"
        }
      ]
    },
    "22":{
      "startPoint":"141670",
      "duration":"3300",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"今"
        },
        {
          "startPoint":"250",
          "duration":"200",
          "str":"天"
        },
        {
          "startPoint":"450",
          "duration":"250",
          "str":"只"
        },
        {
          "startPoint":"700",
          "duration":"200",
          "str":"有"
        },
        {
          "startPoint":"900",
          "duration":"350",
          "str":"残"
        },
        {
          "startPoint":"1250",
          "duration":"249",
          "str":"留"
        },
        {
          "startPoint":"1499",
          "duration":"551",
          "str":"的"
        },
        {
          "startPoint":"2050",
          "duration":"350",
          "str":"躯"
        },
        {
          "startPoint":"2400",
          "duration":"900",
          "str":"壳"
        }
      ]
    },
    "23":{
      "startPoint":"145225",
      "duration":"2800",
      "content":[
        {
          "startPoint":"0",
          "duration":"349",
          "str":"迎"
        },
        {
          "startPoint":"349",
          "duration":"251",
          "str":"接"
        },
        {
          "startPoint":"600",
          "duration":"350",
          "str":"光"
        },
        {
          "startPoint":"950",
          "duration":"350",
          "str":"辉"
        },
        {
          "startPoint":"1300",
          "duration":"600",
          "str":"岁"
        },
        {
          "startPoint":"1900",
          "duration":"900",
          "str":"月"
        }
      ]
    },
    "24":{
      "startPoint":"148475",
      "duration":"4801",
      "content":[
        {
          "startPoint":"0",
          "duration":"450",
          "str":"风"
        },
        {
          "startPoint":"450",
          "duration":"400",
          "str":"雨"
        },
        {
          "startPoint":"850",
          "duration":"251",
          "str":"中"
        },
        {
          "startPoint":"1101",
          "duration":"700",
          "str":"抱"
        },
        {
          "startPoint":"1801",
          "duration":"350",
          "str":"紧"
        },
        {
          "startPoint":"2151",
          "duration":"1600",
          "str":"自"
        },
        {
          "startPoint":"3751",
          "duration":"1050",
          "str":"由"
        }
      ]
    },
    "25":{
      "startPoint":"154556",
      "duration":"3351",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"一"
        },
        {
          "startPoint":"300",
          "duration":"200",
          "str":"生"
        },
        {
          "startPoint":"500",
          "duration":"200",
          "str":"经"
        },
        {
          "startPoint":"700",
          "duration":"200",
          "str":"过"
        },
        {
          "startPoint":"900",
          "duration":"400",
          "str":"彷"
        },
        {
          "startPoint":"1300",
          "duration":"250",
          "str":"徨"
        },
        {
          "startPoint":"1550",
          "duration":"550",
          "str":"的"
        },
        {
          "startPoint":"2100",
          "duration":"400",
          "str":"挣"
        },
        {
          "startPoint":"2500",
          "duration":"851",
          "str":"扎"
        }
      ]
    },
    "26":{
      "startPoint":"158307",
      "duration":"2600",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"自"
        },
        {
          "startPoint":"250",
          "duration":"200",
          "str":"信"
        },
        {
          "startPoint":"450",
          "duration":"350",
          "str":"可"
        },
        {
          "startPoint":"800",
          "duration":"400",
          "str":"改"
        },
        {
          "startPoint":"1200",
          "duration":"250",
          "str":"变"
        },
        {
          "startPoint":"1450",
          "duration":"500",
          "str":"未"
        },
        {
          "startPoint":"1950",
          "duration":"650",
          "str":"来"
        }
      ]
    },
    "27":{
      "startPoint":"161557",
      "duration":"3701",
      "content":[
        {
          "startPoint":"0",
          "duration":"351",
          "str":"问"
        },
        {
          "startPoint":"351",
          "duration":"549",
          "str":"谁"
        },
        {
          "startPoint":"900",
          "duration":"150",
          "str":"又"
        },
        {
          "startPoint":"1050",
          "duration":"450",
          "str":"能"
        },
        {
          "startPoint":"1500",
          "duration":"450",
          "str":"做"
        },
        {
          "startPoint":"1950",
          "duration":"1751",
          "str":"到"
        }
      ]
    },
    "28":{
      "startPoint":"203244",
      "duration":"3351",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"今"
        },
        {
          "startPoint":"300",
          "duration":"200",
          "str":"天"
        },
        {
          "startPoint":"500",
          "duration":"250",
          "str":"只"
        },
        {
          "startPoint":"750",
          "duration":"150",
          "str":"有"
        },
        {
          "startPoint":"900",
          "duration":"400",
          "str":"残"
        },
        {
          "startPoint":"1300",
          "duration":"250",
          "str":"留"
        },
        {
          "startPoint":"1550",
          "duration":"400",
          "str":"的"
        },
        {
          "startPoint":"1950",
          "duration":"450",
          "str":"躯"
        },
        {
          "startPoint":"2400",
          "duration":"951",
          "str":"壳"
        }
      ]
    },
    "29":{
      "startPoint":"206959",
      "duration":"2600",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"迎"
        },
        {
          "startPoint":"250",
          "duration":"200",
          "str":"接"
        },
        {
          "startPoint":"450",
          "duration":"299",
          "str":"光"
        },
        {
          "startPoint":"749",
          "duration":"401",
          "str":"辉"
        },
        {
          "startPoint":"1150",
          "duration":"649",
          "str":"岁"
        },
        {
          "startPoint":"1799",
          "duration":"801",
          "str":"月"
        }
      ]
    },
    "30":{
      "startPoint":"210259",
      "duration":"4650",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"风"
        },
        {
          "startPoint":"350",
          "duration":"350",
          "str":"雨"
        },
        {
          "startPoint":"700",
          "duration":"250",
          "str":"中"
        },
        {
          "startPoint":"950",
          "duration":"550",
          "str":"抱"
        },
        {
          "startPoint":"1500",
          "duration":"450",
          "str":"紧"
        },
        {
          "startPoint":"1950",
          "duration":"1650",
          "str":"自"
        },
        {
          "startPoint":"3600",
          "duration":"1050",
          "str":"由"
        }
      ]
    },
    "31":{
      "startPoint":"216159",
      "duration":"3351",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"一"
        },
        {
          "startPoint":"300",
          "duration":"250",
          "str":"生"
        },
        {
          "startPoint":"550",
          "duration":"200",
          "str":"经"
        },
        {
          "startPoint":"750",
          "duration":"200",
          "str":"过"
        },
        {
          "startPoint":"950",
          "duration":"400",
          "str":"彷"
        },
        {
          "startPoint":"1350",
          "duration":"251",
          "str":"徨"
        },
        {
          "startPoint":"1601",
          "duration":"449",
          "str":"的"
        },
        {
          "startPoint":"2050",
          "duration":"450",
          "str":"挣"
        },
        {
          "startPoint":"2500",
          "duration":"851",
          "str":"扎"
        }
      ]
    },
    "32":{
      "startPoint":"219822",
      "duration":"2800",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"自"
        },
        {
          "startPoint":"300",
          "duration":"250",
          "str":"信"
        },
        {
          "startPoint":"550",
          "duration":"350",
          "str":"可"
        },
        {
          "startPoint":"900",
          "duration":"400",
          "str":"改"
        },
        {
          "startPoint":"1300",
          "duration":"250",
          "str":"变"
        },
        {
          "startPoint":"1550",
          "duration":"450",
          "str":"未"
        },
        {
          "startPoint":"2000",
          "duration":"800",
          "str":"来"
        }
      ]
    },
    "33":{
      "startPoint":"223122",
      "duration":"3601",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"问"
        },
        {
          "startPoint":"350",
          "duration":"450",
          "str":"谁"
        },
        {
          "startPoint":"800",
          "duration":"250",
          "str":"又"
        },
        {
          "startPoint":"1050",
          "duration":"500",
          "str":"能"
        },
        {
          "startPoint":"1550",
          "duration":"400",
          "str":"做"
        },
        {
          "startPoint":"1950",
          "duration":"1651",
          "str":"到"
        }
      ]
    },
    "34":{
      "startPoint":"238930",
      "duration":"3250",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"今"
        },
        {
          "startPoint":"300",
          "duration":"250",
          "str":"天"
        },
        {
          "startPoint":"550",
          "duration":"150",
          "str":"只"
        },
        {
          "startPoint":"700",
          "duration":"200",
          "str":"有"
        },
        {
          "startPoint":"900",
          "duration":"450",
          "str":"残"
        },
        {
          "startPoint":"1350",
          "duration":"100",
          "str":"留"
        },
        {
          "startPoint":"1450",
          "duration":"501",
          "str":"的"
        },
        {
          "startPoint":"1951",
          "duration":"449",
          "str":"躯"
        },
        {
          "startPoint":"2400",
          "duration":"850",
          "str":"壳"
        }
      ]
    },
    "35":{
      "startPoint":"242530",
      "duration":"2749",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"迎"
        },
        {
          "startPoint":"250",
          "duration":"250",
          "str":"接"
        },
        {
          "startPoint":"500",
          "duration":"350",
          "str":"光"
        },
        {
          "startPoint":"850",
          "duration":"400",
          "str":"辉"
        },
        {
          "startPoint":"1250",
          "duration":"600",
          "str":"岁"
        },
        {
          "startPoint":"1850",
          "duration":"899",
          "str":"月"
        }
      ]
    },
    "36":{
      "startPoint":"245730",
      "duration":"4800",
      "content":[
        {
          "startPoint":"0",
          "duration":"400",
          "str":"风"
        },
        {
          "startPoint":"400",
          "duration":"450",
          "str":"雨"
        },
        {
          "startPoint":"850",
          "duration":"250",
          "str":"中"
        },
        {
          "startPoint":"1100",
          "duration":"600",
          "str":"抱"
        },
        {
          "startPoint":"1700",
          "duration":"450",
          "str":"紧"
        },
        {
          "startPoint":"2150",
          "duration":"1550",
          "str":"自"
        },
        {
          "startPoint":"3700",
          "duration":"1100",
          "str":"由"
        }
      ]
    },
    "37":{
      "startPoint":"251949",
      "duration":"3350",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"一"
        },
        {
          "startPoint":"250",
          "duration":"199",
          "str":"生"
        },
        {
          "startPoint":"449",
          "duration":"201",
          "str":"经"
        },
        {
          "startPoint":"650",
          "duration":"149",
          "str":"过"
        },
        {
          "startPoint":"799",
          "duration":"401",
          "str":"彷"
        },
        {
          "startPoint":"1200",
          "duration":"199",
          "str":"徨"
        },
        {
          "startPoint":"1399",
          "duration":"551",
          "str":"的"
        },
        {
          "startPoint":"1950",
          "duration":"350",
          "str":"挣"
        },
        {
          "startPoint":"2300",
          "duration":"1050",
          "str":"扎"
        }
      ]
    },
    "38":{
      "startPoint":"255487",
      "duration":"2717",
      "content":[
        {
          "startPoint":"0",
          "duration":"277",
          "str":"自"
        },
        {
          "startPoint":"277",
          "duration":"249",
          "str":"信"
        },
        {
          "startPoint":"526",
          "duration":"353",
          "str":"可"
        },
        {
          "startPoint":"879",
          "duration":"399",
          "str":"改"
        },
        {
          "startPoint":"1278",
          "duration":"376",
          "str":"变"
        },
        {
          "startPoint":"1654",
          "duration":"313",
          "str":"未"
        },
        {
          "startPoint":"1967",
          "duration":"750",
          "str":"来"
        }
      ]
    },
    "39":{
      "startPoint":"258753",
      "duration":"3903",
      "content":[
        {
          "startPoint":"0",
          "duration":"400",
          "str":"问"
        },
        {
          "startPoint":"400",
          "duration":"451",
          "str":"谁"
        },
        {
          "startPoint":"851",
          "duration":"250",
          "str":"又"
        },
        {
          "startPoint":"1101",
          "duration":"501",
          "str":"能"
        },
        {
          "startPoint":"1602",
          "duration":"400",
          "str":"做"
        },
        {
          "startPoint":"2002",
          "duration":"1901",
          "str":"到"
        }
      ]
    },
    "40":{
      "startPoint":"274632",
      "duration":"3300",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"今"
        },
        {
          "startPoint":"250",
          "duration":"199",
          "str":"天"
        },
        {
          "startPoint":"449",
          "duration":"150",
          "str":"只"
        },
        {
          "startPoint":"599",
          "duration":"200",
          "str":"有"
        },
        {
          "startPoint":"799",
          "duration":"351",
          "str":"残"
        },
        {
          "startPoint":"1150",
          "duration":"250",
          "str":"留"
        },
        {
          "startPoint":"1400",
          "duration":"550",
          "str":"的"
        },
        {
          "startPoint":"1950",
          "duration":"400",
          "str":"躯"
        },
        {
          "startPoint":"2350",
          "duration":"950",
          "str":"壳"
        }
      ]
    },
    "41":{
      "startPoint":"278282",
      "duration":"2650",
      "content":[
        {
          "startPoint":"0",
          "duration":"249",
          "str":"迎"
        },
        {
          "startPoint":"249",
          "duration":"150",
          "str":"接"
        },
        {
          "startPoint":"399",
          "duration":"351",
          "str":"光"
        },
        {
          "startPoint":"750",
          "duration":"449",
          "str":"辉"
        },
        {
          "startPoint":"1199",
          "duration":"501",
          "str":"岁"
        },
        {
          "startPoint":"1700",
          "duration":"950",
          "str":"月"
        }
      ]
    },
    "42":{
      "startPoint":"281581",
      "duration":"4751",
      "content":[
        {
          "startPoint":"0",
          "duration":"350",
          "str":"风"
        },
        {
          "startPoint":"350",
          "duration":"350",
          "str":"雨"
        },
        {
          "startPoint":"700",
          "duration":"250",
          "str":"中"
        },
        {
          "startPoint":"950",
          "duration":"550",
          "str":"抱"
        },
        {
          "startPoint":"1500",
          "duration":"400",
          "str":"紧"
        },
        {
          "startPoint":"1900",
          "duration":"1401",
          "str":"自"
        },
        {
          "startPoint":"3301",
          "duration":"1450",
          "str":"由"
        }
      ]
    },
    "43":{
      "startPoint":"287582",
      "duration":"3250",
      "content":[
        {
          "startPoint":"0",
          "duration":"250",
          "str":"一"
        },
        {
          "startPoint":"250",
          "duration":"200",
          "str":"生"
        },
        {
          "startPoint":"450",
          "duration":"150",
          "str":"经"
        },
        {
          "startPoint":"600",
          "duration":"200",
          "str":"过"
        },
        {
          "startPoint":"800",
          "duration":"400",
          "str":"彷"
        },
        {
          "startPoint":"1200",
          "duration":"250",
          "str":"徨"
        },
        {
          "startPoint":"1450",
          "duration":"500",
          "str":"的"
        },
        {
          "startPoint":"1950",
          "duration":"450",
          "str":"挣"
        },
        {
          "startPoint":"2400",
          "duration":"850",
          "str":"扎"
        }
      ]
    },
    "44":{
      "startPoint":"291176",
      "duration":"2800",
      "content":[
        {
          "startPoint":"0",
          "duration":"300",
          "str":"自"
        },
        {
          "startPoint":"300",
          "duration":"250",
          "str":"信"
        },
        {
          "startPoint":"550",
          "duration":"301",
          "str":"可"
        },
        {
          "startPoint":"851",
          "duration":"449",
          "str":"改"
        },
        {
          "startPoint":"1300",
          "duration":"251",
          "str":"变"
        },
        {
          "startPoint":"1551",
          "duration":"450",
          "str":"未"
        },
        {
          "startPoint":"2001",
          "duration":"799",
          "str":"来"
        }
      ]
    },
    "45":{
      "startPoint":"294575",
      "duration":"301942",
      "content":[
        {
          "startPoint":"0",
          "duration":"400",
          "str":"问"
        },
        {
          "startPoint":"400",
          "duration":"451",
          "str":"谁"
        },
        {
          "startPoint":"851",
          "duration":"299",
          "str":"又"
        },
        {
          "startPoint":"1150",
          "duration":"400",
          "str":"能"
        },
        {
          "startPoint":"1550",
          "duration":"451",
          "str":"做"
        },
        {
          "startPoint":"2001",
          "duration":"1000",
          "str":"到"
        }
      ]
    }
  },
};
